### ISSUE TITLE
NiceHash  is missing from the Pool Balances table in the GUI

### ISSUE THREAD

**Issue by JimKnightster** [grantemsley/MultiPoolMiner#10]
Nicehash pool balance is missing

**Comment by grantemsley** [comment]
Yup.  I've only written balance checking scripts for the pools I personally use so far.

Feel free to write one for nicehash and submit a PR!

**Comment by JimKnightster** [comment]
:) yeah I just read that on your notes, my bad, I will try if I can figure it out... I dabble in powershell, but thats about it.

**Comment by JimKnightster** [comment]
OK so I did it, Nicehash now displays in my GUI, I'm not sure how to do a PR but I will figure it out.   Not sure I did it correctly, but its up.  I cant test the verified balance as I have none right now, but do have some pending BTC and that seems to work ok.

**Comment by grantemsley** [comment]
Great!  

I don't think nicehash has the same distinction between pending and confirmed balances - so the entire nicehash balance should probably be under confirmed.

If you cant figure out the pull request thing and don't care about having credit for it in the git commit logs, you can just post the code to https://gist.github.com/ and I can add it from there.

**Comment by JimKnightster** [comment]
Yeah they don't I ended  up having to do 2 separate API calls and adding all of the algo's up for the unconfirmed balance.  Not difficult just had to find out where they were.  I don't care about credit, just happy to contribute.  
https://gist.github.com/JimKnightster/38124acceb4c2bae9f21c035b5fce56b

FYI, requires API_ID and API_KEY (Read only key) from NH
