### ISSUE TITLE
Active Miners does not show active miner

### ISSUE THREAD

**Issue by JimKnightster** [grantemsley/MultiPoolMiner#12]
I have 2 rigs, 1 with 2 AMD cards and a CPU (my gaming rig) the other i built back in November with 6 AMD cards (mining rig).  On my gaming rig the active miners window shows up and updates and all is well.  On my mining rig however nothing ever shows.  Its mining (I can see it on MPM.IO) and I can see the logs.  The worker/BTC status at the bottom is working as well, just no miner info in Active Miners.   This issue is why I thought 'Start when idle' didn't work.  

Let me know if you need to look at any logs or such.

**Comment by grantemsley** [comment]
At the moment I'm not worried about it too much - I'm in the middle of completely rewriting the part of the code that reads the active miners, so any bugs there will be removed (and probably replace with new, more exciting bugs).

**Comment by JimKnightster** [comment]
good deal, cant wait to see the changes.

**Comment by grantemsley** [comment]
Launcher rewritten to use API for this data
