### ISSUE TITLE
Errors on starting start.bat on first time

### ISSUE THREAD

**Issue by m-bosch** [grantemsley/MultiPoolMiner#19]
Hi @grantemsley im getting the following errors when I run start.bat

`C:\Users\digifactory\Desktop\MultiPoolMiner\MultiPoolMiner>powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "& .\multipoolminer.ps1"
WARNING: CPU Mining limited to 1/2 of logical processors
Transcript started, output file is .\Logs\MultiPoolMiner_2018-07-09_08-11-21.txt
Starting MultiPoolMiner® v3 © 2017-2018 MultiPoolMiner.io
Using configuration file (C:\Users\digifactory\Desktop\MultiPoolMiner\MultiPoolMiner\Config.txt).
Start-APIServer : Cannot process argument transformation on parameter 'RemoteAPI'. Cannot convert value "System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
At C:\Users\digifactory\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:188 char:36
+         Start-APIServer -RemoteAPI:$Config.RemoteAPI
+                                    ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-APIServer], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Start-APIServer

The property 'Version' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\digifactory\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:189 char:9
+         $API.Version = $Version
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'Devices' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\digifactory\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:190 char:9
+         $API.Devices = $Devices
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Mining for you. Donation run will start in 00 hour(s) 50 minute(s).
The property 'Config' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\digifactory\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:239 char:5
+     $API.Config = $Config
+     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Updating exchange rates from Coinbase.
Getting pool balances.
The property 'Balances' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\x\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:276 char:9
+         $API.Balances = $Balances
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'Devices' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\x\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:283 char:5
+     $API.Devices = $Devices
+     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Loading saved statistics.
The property 'Stats' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\x\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:290 char:5
+     $API.Stats = $Stats
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound`

What did I configured wrong? I didn't change anything in the MultiPoolMiner.ps1

**Comment by m-bosch** [comment]
The start.bat file and command gets running. now it is benchmarking (210 to go (OMG)). but in the end of the log the following warning occurs:

`Exchange rates: 1 BTC = EUR 5713.52 = USD 6705.00
The property 'WatchdogTimers' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\x\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:701 char:5
+     $API.WatchdogTimers = $WatchdogTimers
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'ActiveMiners' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\x\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:704 char:5
+     $API.ActiveMiners = $ActiveMiners
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'RunningMiners' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\x\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:705 char:26
+ ... ingMiners = $RunningMiners = $ActiveMiners | Where-Object {$_.GetStat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'FailedMiners' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\x\Desktop\MultiPoolMiner\MultiPoolMiner\MultiPoolMiner.ps1:706 char:5
+     $API.FailedMiners = $ActiveMiners | Where-Object {$_.GetStatus()  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Benchmarking watchdog sensitive algorithm or miner. Increasing interval time temporarily to 10x interval (600 seconds).
Start waiting before next run.
`

**Comment by m-bosch** [comment]
As far as I can see it has to do something with the params for the web pages (these aren't working at my system btw). but I don't know what you want to configure for that.

**Comment by m-bosch** [comment]
Hi @grantemsley,
after settings the following parameter

`"RemoteAPI":  false,`

the problem is solved, although I don't know what this parameter can do, and how to set it. can you help me out? Probably it has something to do with your web pages?

**Comment by grantemsley** [comment]
I don't use start.bat at all so I don't update it.  My version expects your config.txt file to be fully filled out like I showed in your other issue.

The RemoteAPI setting is to let you use the web interface from another computer on the network.

The errors you were getting meant the API couldn't start.  Maybe you didn't click ok to the UAC prompt you would have gotten on the first run when remoteapi is true (it needs admin privileges to give itself permission to listen on a port).

**Comment by m-bosch** [comment]
I found the error, it was that the remoteAPI wasn't a boolean but a string "false" instead of false....

Stupid me, rookie mistake.

Since this morning t run it by the launcher.bat.

in the version of Aaron i set the start.bat file in my auto-boot of windows so it starts on every reboot. is this also possible with your launcher.bat? I probably should check the start on idle?

**Comment by grantemsley** [comment]
Yup, check start on idle (that setting does get saved) and launcher.bat to auto start.  Make sure you disable the other one.

**Comment by m-bosch** [comment]
Awesome, compliments on these features very nice!

When there will be a second miner I probably will have some question how to connect both on these monitor but that will take a while, first the extra cards in this miner :-)


PS 210 to benchmark..... OMG 210*600 seconds... :P

**Comment by grantemsley** [comment]
Most of them won't take 600 seconds.  Only the PHI and X16r/s algorithms need that long.  The rest only run for a minute each.

But that's why I setup my update scripts to only clear the stats for miners that change - so you don't need to rebenchmark with each update (though you will have to if you add or remove cards).
