### ISSUE TITLE
Excavator window doesnt close

### ISSUE THREAD

**Issue by m-bosch** [grantemsley/MultiPoolMiner#22]
When MPM switches from excavator to other miner the Windows wont close. All other miners do.

**Comment by grantemsley** [comment]
That's just how excavator works.  It does stop mining, so it doesn't cause any issues, but the window stays open and is reused if it switches back to excavator.

Bugs me too...but not enough to actually do anything about it thus far.

**Comment by m-bosch** [comment]
As far as it doesn't cost any resources I won't mind either, well not enough to complain about it anymore :-)
