### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by JimKnightster** [grantemsley/MultiPoolMiner#9]
I see this error alot (doing benchmarks for a new install with the BIN folder copied from my main MPM 2.7.2.7 folder:
![image](https://user-images.githubusercontent.com/13444381/38068286-60e4e192-32de-11e8-9b88-e2f8d39cd840.png)

**Comment by grantemsley** [comment]
Yeah that's a known issue with some of the test code I have in my fork...it's looking for the log file a moment before it actually gets created.  Shouldn't cause any issues besides the annoying warning though.

**Comment by JimKnightster** [comment]
I actually noticed some of the log files in the format with the date in front, created but all 0 bytes in the log folder.  Started looking through the code, but got lost
